### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fouda4ever** [byohay/anki-smart-copy#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-09-04 19:07:36

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-18>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\Mohammad\AppData\Roaming\Anki2\addons21\799647424\main.py", line 183, in on_bridge_cmd
    _old(editor, command)
  File "aqt\editor.py", line 403, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1481, in __call__
  File "C:\Users\Mohammad\AppData\Roaming\Anki2\addons21\2026164196\__init__.py", line 185, in smart_copy
    if not per_character_configuration.filter_characters(character):
TypeError: 'NoneType' object is not callable

**Comment by jjgerr** [comment]
I just downloaded and configured this add-on but am getting the same error. Any luck since posting this?

**Comment by fouda4ever** [comment]
no unfortunately

**Comment by byohay** [comment]
@fouda4ever @jjgerr sorry for the delay! I believe I fixed it (though I wasn't able to reproduce it). I'll upload a new version soon.

**Comment by byohay** [comment]
I uploaded a new version. PLMK if it was fixed.
